apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e2bmbw9pt-go 
  janus-idp.io/tekton: e2bmbw9pt-go
  backstage.io/kubernetes-id: e2bmbw9pt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e2bmbw9pt-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml